name: publish
on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            # - run: npm run format
            # - run: npm run build
            # - run: npm run test
            - name: Update package version
              run: |
                npm run update:version:to:tag
                git config --global user.name github-actions
                git config --global user.email github-actions@github.com
                git add .
                git commit -m "chore: updating package to reflect $GITHUB_REF_NAME"
                git branch tmp
                git checkout adding-updating-version-script
                git merge tmp
                git branch -d tmp
                git push
            # - run: npm publish --access public
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
